import assert from "node:assert/strict";
import { moriSeed, checkoutMori, addMoriCart, setMoriOrderStatus, slotRemaining, localDate } from "../lib/mori-domain.ts";

const nextDay = new Date(); nextDay.setDate(nextDay.getDate() + 1);
const date = localDate(nextDay);
let data = { ...moriSeed(), signedIn: true };
data = addMoriCart(data, { kind: "product", id: "rose-mug", quantity: 2 });
data = addMoriCart(data, { kind: "workshop", id: "wheel", quantity: 2, date, time: "10:00" });
const form = { name: "Demo", phone: "0900000000", email: "demo@example.com", address: "Demo address", note: "", delivery: "shipping", payment: "demo" };
data = checkoutMori(data, form, "test-1");
assert.equal(data.orders.length, 1);
assert.equal(data.products[0].stock, 10);
assert.equal(data.cart.length, 0);
assert.equal(data.orders[0].total, 4720);
assert.equal(data.orders[0].shipping, 0);
assert.equal(slotRemaining(data, "wheel", date, "10:00"), 2);
assert.equal(checkoutMori(data, form, "test-1"), data, "duplicate submission must be idempotent");
assert.throws(() => addMoriCart(data, { kind: "workshop", id: "wheel", quantity: 3, date, time: "10:00" }), /名額不足/);
assert.throws(() => addMoriCart(data, { kind: "product", id: "rose-mug", quantity: 11 }), /庫存不足/);
data = setMoriOrderStatus(data, "test-1", "已取消");
assert.equal(data.products[0].stock, 12);
assert.equal(slotRemaining(data, "wheel", date, "10:00"), 4);
assert.equal(setMoriOrderStatus(data, "test-1", "已取消"), data);
assert.throws(() => setMoriOrderStatus(data, "test-1", "已確認"), /無法重新啟用/);
data = addMoriCart(data, { kind: "product", id: "sage-cup", quantity: 1 });
assert.throws(() => checkoutMori(data, { ...form, email: "invalid" }, "test-2"), /Email/);
assert.throws(() => checkoutMori(data, { ...form, address: "" }, "test-2"), /地址/);
const pending = checkoutMori(data, { ...form, payment: "transfer" }, "test-2");
assert.equal(pending.orders[0].total, 560);
assert.equal(pending.orders[0].paid, false);
assert.equal(pending.orders[0].shipping, 80);
assert.equal(JSON.parse(JSON.stringify(pending)).orders[0].id, "test-2");
console.log("MORI flow checks passed: checkout, totals, stock, capacity, cancellation, duplicate submission, validation.");
